server:
  port: 2000
spring:
  application:
    name: funding-mysql
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project_funding?serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
logging:
  level:
    top.headfirst.funding.mapper: debug
    top.headfirst.funding.test: debug